### ISSUE TITLE
User provided comments

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som-shiny#10]
Can users log issue with the datasets, additional shiny features, etc and record these on the server, an email, or **API to github repo?**

**Comment by nathanhwangbo** [comment]
Started work on this in a branch. The skeleton for the UI is pretty much all there, and I'm working on writing an issue through the API. 

The problem is that the user needs write authorization in order to make an issue. Derek suggested maybe creating a machine user (a dummy account with authorization), but Julien and I are going to look into other methods (eg deploy keys, GitHub apps) that might be better practice.
